{% set name = "grblas" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/jim22k/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: --- FILL THIS IN ---

build:
  number: 0

requirements:
  build:
    - python >=3.5
    - cffi
    - ss_graphblas ==3.1.1
    - pytest-runner
  
  host:
    - python >=3.5
    - cffi
    - ss_graphblas ==3.1.1
    - pytest-runner

  run:
    - python >=3.5
    - cffi
    - ss_graphblas ==3.1.1
    - numba

about:
  home: https://github.com/jim22k/grblas
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python wrapper around GraphBLAS'
  description: |
    Python wrapper around GraphBLAS.
  dev_url: https://github.com/jim22k/grblas

extra:
  recipe-maintainers:
    - jim22k