# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py

# Try to make build faster with mamba. See:
# https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/env.yml
