[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >=64",
    "setuptools-git-versioning",
]

[project]
name = "python-graphblas"
dynamic = ["version"]
description = "Python library for GraphBLAS: high-performance sparse linear algebra for scalable graph analytics"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Erik Welch", email = "erik.n.welch@gmail.com"},
    {name = "Jim Kitchen"},
    {name = "Python-graphblas contributors"},
]
maintainers = [
    {name = "Erik Welch", email = "erik.n.welch@gmail.com"},
    {name = "Jim Kitchen", email = "jim22k@gmail.com"},
    {name = "Sultan Orazbayev", email = "contact@econpoint.com"},
]
keywords = [
    "graphblas",
    "graph",
    "sparse",
    "matrix",
    "lagraph",
    "suitesparse",
    "Networks",
    "Graph Theory",
    "Mathematics",
    "network",
    "discrete mathematics",
    "math",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
    "Intended Audience :: Developers",
    "Intended Audience :: Other Audience",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "suitesparse-graphblas >=7.4.0.0, <7.5",
    "numpy >=1.21",
    "numba >=0.55",
    "donfig >=0.6",
    "pyyaml >=5.4",
]

[project.urls]
homepage = "https://github.com/python-graphblas/python-graphblas"
documentation = "https://python-graphblas.readthedocs.io"
repository = "https://github.com/python-graphblas/python-graphblas"
changelog = "https://github.com/python-graphblas/python-graphblas/releases"

[project.optional-dependencies]
repr = [
    "pandas >=1.2",
]
io = [
    "networkx >=2.8",
    "scipy >=1.8",
    "awkward >=1.9",
    "sparse >=0.12",
    "fast-matrix-market >=1.4.5",
]
viz = [
    "matplotlib >=3.5",
]
test = [
    "pytest",
    "packaging",
    "pandas >=1.2",
    "scipy >=1.8",
    "tomli",
]
complete = [
    "pandas >=1.2",
    "networkx >=2.8",
    "scipy >=1.8",
    "awkward >=1.9",
    "sparse >=0.12",
    "fast-matrix-market >=1.4.5",
    "matplotlib >=3.5",
    "pytest",
    "packaging",
    "tomli",
]

[tool.setuptools]
# Let's be explicit
# $ python -c 'from setuptools import find_packages ; [print(x) for x in sorted(find_packages())]'
# $ find graphblas/ -name __init__.py -print | sort | sed -e 's/\/__init__.py//g' -e 's/\//./g'
# $ python -c 'import tomli ; [print(x) for x in sorted(tomli.load(open("pyproject.toml", "rb"))["tool"]["setuptools"]["packages"])]'
packages = [
    "graphblas",
    "graphblas.agg",
    "graphblas.binary",
    "graphblas.core",
    "graphblas.core.operator",
    "graphblas.core.ss",
    "graphblas.indexunary",
    "graphblas.monoid",
    "graphblas.op",
    "graphblas.semiring",
    "graphblas.select",
    "graphblas.ss",
    "graphblas.tests",
    "graphblas.unary",
]

[tool.setuptools-git-versioning]
enabled = true
dev_template = "{tag}+{ccount}.g{sha}"
dirty_template = "{tag}+{ccount}.g{sha}.dirty"

[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
profile = "black"
skip_gitignore = true
float_to_top = true
default_section = "THIRDPARTY"
known_first_party = "graphblas"
line_length = 100

[tool.pytest.ini_options]
testpaths = "graphblas/tests"
xfail_strict = true
markers = [
    "slow: Skipped unless --runslow passed",
]
filterwarnings = [
    # See: https://docs.python.org/3/library/warnings.html#describing-warning-filters
    # and: https://docs.pytest.org/en/7.2.x/how-to/capture-warnings.html#controlling-warnings
    "error",
    # MAINT: we can drop support for sparse <0.13 at any time
    "ignore:`np.bool` is a deprecated alias:DeprecationWarning:sparse._umath",  # sparse <0.13
    # sparse 0.14.0 (2022-02-24) began raising this warning; it has been reported and fixed upstream.
    "ignore:coords should be an ndarray. This will raise a ValueError:DeprecationWarning:sparse._coo.core",

    # setuptools v67.3.0 deprecated `pkg_resources.declare_namespace` on 13 Feb 2023. See:
    # https://setuptools.pypa.io/en/latest/history.html#v67-3-0
    # MAINT: check if this is still necessary in 2025
    "ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning:pkg_resources",
    # And this deprecation warning was added in setuptools v67.5.0 (8 Mar 2023). See:
    # https://setuptools.pypa.io/en/latest/history.html#v67-5-0
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning:pkg_resources",
]

[tool.coverage.run]
branch = true
source = ["graphblas"]
omit = [
    "graphblas/viz.py",  # TODO: test and get coverage for viz.py
]

[tool.coverage.report]
ignore_errors = false
precision = 1
fail_under = 0
skip_covered = true
skip_empty = true
exclude_lines = [
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
]

[tool.codespell]
ignore-words-list = "coo,ba"

[tool.ruff]
# https://github.com/charliermarsh/ruff/
line-length = 100
target-version = "py38"
select = [
    # Have we enabled too many checks that they'll become a nuisance? We'll see...
    "F",  # pyflakes
    "E",  # pycodestyle Error
    "W",  # pycodestyle Warning
    # "C90",  # mccabe (Too strict, but maybe we should make things less complex)
    # "I",  # isort (Should we replace `isort` with this?)
    "N",  # pep8-naming
    "D",  # pydocstyle
    "UP",  # pyupgrade
    "YTT",  # flake8-2020
    # "ANN",  # flake8-annotations (We don't use annotations yet)
    "S",  # bandit
    # "BLE",  # flake8-blind-except (Maybe consider)
    # "FBT",  # flake8-boolean-trap (Why?)
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "COM",  # flake8-commas
    "C4",  # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "T10",  # flake8-debugger
    # "DJ",  # flake8-django (We don't use django)
    # "EM",  # flake8-errmsg (Perhaps nicer, but too much work)
    "EXE",  # flake8-executable
    "ISC",  # flake8-implicit-str-concat
    # "ICN",  # flake8-import-conventions (Doesn't allow "_" prefix such as `_np`)
    "G",  # flake8-logging-format
    "INP",  # flake8-no-pep420
    "PIE",  # flake8-pie
    "T20",   # flake8-print
    # "PYI",  # flake8-pyi (We don't have stub files yet)
    "PT",  # flake8-pytest-style
    "Q",  # flake8-quotes
    "RSE", # flake8-raise
    "RET",  # flake8-return
    # "SLF",  # flake8-self (We can use our own private variables--sheesh!)
    "SIM",  # flake8-simplify
    # "TID",  # flake8-tidy-imports (Rely on isort and our own judgement)
    # "TCH",  # flake8-type-checking (Note: figure out type checking later)
    # "ARG",  # flake8-unused-arguments (Sometimes helpful, but too strict)
    "PTH",  # flake8-use-pathlib (Often better, but not always)
    # "ERA",  # eradicate (We like code in comments!)
    # "PD",  # pandas-vet (Intended for scripts that use pandas, not libraries)
    "PGH",  # pygrep-hooks
    "PL",  # pylint
    "PLC",  # pylint Convention
    "PLE",  # pylint Error
    "PLR",  # pylint Refactor
    "PLW",  # pylint Warning
    "TRY",  # tryceratops
    "NPY",  # NumPy-specific rules
    "RUF",  # ruff-specific rules
    "ALL",  # Try new categories by default (making the above list unnecessary)
]
external = [
    # noqa codes that ruff doesn't know about: https://github.com/charliermarsh/ruff#external
]
ignore = [
    # Would be nice to fix these
    "D100",  # Missing docstring in public module
    "D101",  # Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in public function
    "D104",  # Missing docstring in public package
    "D105",  # Missing docstring in magic method
    # "D107",  # Missing docstring in `__init__`
    "D205",  # 1 blank line required between summary line and description
    "D401",  # First line of docstring should be in imperative mood:
    # "D417",  # Missing argument description in the docstring:
    "PLE0605",  # Invalid format for `__all__`, must be `tuple` or `list` (Note: broken in v0.0.237)

    # Maybe consider
    # "SIM300",  # Yoda conditions are discouraged, use ... instead (Note: we're not this picky)
    # "SIM401",  # Use dict.get ... instead of if-else-block (Note: if-else better for coverage and sometimes clearer)
    "TRY004",  # Prefer `TypeError` exception for invalid type (Note: good advice, but not worth the nuisance)
    "TRY200",  # Use `raise from` to specify exception cause (Note: sometimes okay to raise original exception)

    # Intentionally ignored
    "COM812",  # Trailing comma missing
    "D203",  # 1 blank line required before class docstring (Note: conflicts with D211, which is preferred)
    "D400",  # First line should end with a period (Note: prefer D415, which also allows "?" and "!")
    "N801",  # Class name ... should use CapWords convention (Note:we have a few exceptions to this)
    "N802",  # Function name ... should be lowercase
    "N803",  # Argument name ... should be lowercase (Maybe okay--except in tests)
    "N806",  # Variable ... in function should be lowercase
    "N807",  # Function name should not start and end with `__`
    "N818",  # Exception name ... should be named with an Error suffix (Note: good advice)
    "PLR0911",  # Too many return statements
    "PLR0912",  # Too many branches
    "PLR0913",  # Too many arguments to function call
    "PLR0915",  # Too many statements
    "PLR2004",  # Magic number used in comparison, consider replacing magic with a constant variable
    "PLW0603",  # Using the global statement to update ... is discouraged (Note: yeah, discouraged, but too strict)
    "PLW2901",  # Outer for loop variable ... overwritten by inner assignment target (Note: good advice, but too strict)
    "RET502",  # Do not implicitly `return None` in function able to return non-`None` value
    "RET503",  # Missing explicit `return` at the end of function able to return non-`None` value
    "RET504",  # Unnecessary variable assignment before `return` statement
    "S110",  # `try`-`except`-`pass` detected, consider logging the exception (Note: good advice, but we don't log)
    "S112",  # `try`-`except`-`continue` detected, consider logging the exception (Note: good advice, but we don't log)
    "SIM102",  # Use a single `if` statement instead of nested `if` statements (Note: often necessary)
    "SIM105",  # Use contextlib.suppress(...) instead of try-except-pass (Note: try-except-pass is much faster)
    "SIM108",  # Use ternary operator ... instead of if-else-block (Note: if-else better for coverage and sometimes clearer)
    "TRY003",  # Avoid specifying long messages outside the exception class (Note: why?)

    # Ignored categories
    "C90",  # mccabe (Too strict, but maybe we should make things less complex)
    "I",  # isort (Should we replace `isort` with this?)
    "ANN",  # flake8-annotations (We don't use annotations yet)
    "BLE",  # flake8-blind-except (Maybe consider)
    "FBT",  # flake8-boolean-trap (Why?)
    "DJ",  # flake8-django (We don't use django)
    "EM",  # flake8-errmsg (Perhaps nicer, but too much work)
    "ICN",  # flake8-import-conventions (Doesn't allow "_" prefix such as `_np`)
    "PYI",  # flake8-pyi (We don't have stub files yet)
    "SLF",  # flake8-self (We can use our own private variables--sheesh!)
    "TID",  # flake8-tidy-imports (Rely on isort and our own judgement)
    "TCH",  # flake8-type-checking (Note: figure out type checking later)
    "ARG",  # flake8-unused-arguments (Sometimes helpful, but too strict)
    "ERA",  # eradicate (We like code in comments!)
    "PD",  # pandas-vet (Intended for scripts that use pandas, not libraries)
]

[tool.ruff.per-file-ignores]
"graphblas/core/agg.py" = ["F401", "F403"]  # Deprecated
"graphblas/core/operator/base.py" = ["S102"]  # exec is used for UDF
"graphblas/core/ss/matrix.py" = ["NPY002"]  # numba doesn't support rng generator yet
"graphblas/core/ss/vector.py" = ["NPY002"]  # numba doesn't support rng generator yet
"graphblas/ss/_core.py" = ["N999"]  # We want _core.py to be underscopre
# Allow useless expressions, assert, pickle, RNG, print, no docstring, and yoda in tests
"graphblas/tests/*py" = ["B018", "S101", "S301", "S311", "T201", "D103", "D100", "SIM300"]
"graphblas/tests/test_formatting.py" = ["E501"]  # Allow long lines
"graphblas/**/__init__.py" = ["F401"]  # Allow unused imports (w/o defining `__all__`)
"scripts/*.py" = ["INP001"]  # Not a package
"scripts/create_pickle.py" = ["F403", "F405"]  # Allow `from foo import *`
"docs/*.py" = ["INP001"]  # Not a package

[tool.ruff.flake8-builtins]
builtins-ignorelist = ["copyright", "format", "min", "max"]

[tool.ruff.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.pylint.messages_control]
# To run a single check, do: pylint graphblas --disable E,W,R,C,I --enable assignment-from-no-return
max-line-length = 100
py-version = "3.8"
enable = ["I"]
disable = [
    # Error
    "assignment-from-no-return",

    # Warning
    "arguments-differ",
    "arguments-out-of-order",
    "expression-not-assigned",
    "fixme",
    "global-statement",
    "non-parent-init-called",
    "redefined-builtin",
    "redefined-outer-name",
    "super-init-not-called",
    "unbalanced-tuple-unpacking",
    "unnecessary-lambda",
    "unspecified-encoding",
    "unused-argument",
    "unused-variable",

    # Refactor
    "cyclic-import",
    "duplicate-code",
    "inconsistent-return-statements",
    "too-few-public-methods",

    # Convention
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-many-lines",

    # Intentionally turned off
    # error
    "class-variable-slots-conflict",
    "invalid-unary-operand-type",
    "no-member",
    "no-name-in-module",
    "not-an-iterable",
    "too-many-function-args",
    "unexpected-keyword-arg",
    # warning
    "broad-except",
    "pointless-statement",
    "protected-access",
    "undefined-loop-variable",
    "unused-import",
    # refactor
    "comparison-with-itself",
    "too-many-arguments",
    "too-many-boolean-expressions",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-locals",
    "too-many-nested-blocks",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements",
    # convention
    "import-outside-toplevel",
    "invalid-name",
    "line-too-long",
    "singleton-comparison",
    "single-string-used-for-slots",
    "unidiomatic-typecheck",
    "unnecessary-dunder-call",
    "wrong-import-order",
    "wrong-import-position",
    # informative
    "locally-disabled",
    "suppressed-message",
]
